### ISSUE TITLE
Add graphql and migrations checks into pre-commit hooks

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor#4613]
It would be useful if users could be alerted before creating a commit that their definitions and/or migrations are out of date.

We could simply re-implement our travis checks into the pre-commit file. For example, for migrations:
```yaml
-   repo: local
    hooks:
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: bash -c "./manage.py makemigrations --check --dry-run"
      files: "models\\.py$"
      stages: [commit]
```
