### ISSUE TITLE
Less than obvious how to get a demo running from docker-compose on a non-local system

### ISSUE THREAD

**Issue by dsoprea** [mirumee/saleor#6580]
### What I'm trying to achieve

Get a simple demo of Saleor running from a server using docker-compose.

### Steps to reproduce the problem

Ran the setup steps here from my server (which means that localhost won't be in the URL): 

https://github.com/mirumee/saleor-platform

### What I expected to happen

Expected site to come up.

I'm pretty confused between what _ALLOWED_CLIENT_HOSTS_, _ALLOWED_HOSTS_, and _API_URL_ should be, and which services/images in the docker-compose config should have them.

It seems like _ALLOWED_CLIENT_HOSTS_ and/or _ALLOWED_HOSTS_ supposedely support asterisks but adding them doesn't seem to have made much of a difference. Although not captured in the screenshots, I previously got errors that recommended that I add my IP to `ALLOWED_CLIENT_HOSTS`, though it's not quite acceptable to provide an IP here as I require it to be completely permissive. Hence, the asterisk.

When I set _API_URL_, I still get lots of stuff in the browser complaining about not being able to hit "localhost:8000". I even get the issues when I kill the volumes and restart, just to ensure I don't have any poisoned state.

I'm also getting a ton of `System limit for number of file watchers reached` messages in the console. Most of it runs beyond my history limit, but it seems to be related to Node assets.

All of the sites/services (:3000, :9000, and :8000) are returning errors. Obviously, :8000 seems like it should be attended-to, first.

This is my current _docker-compose.yml_ (the server is 192.168.10.5):

```
version: '2'

services:
  api:
    ports:
      - 8000:8000
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      - ./saleor/saleor/:/app/saleor:Z
      - ./saleor/templates/:/app/templates:Z
      - ./saleor/tests/:/app/tests
      # shared volume between worker and api for media
      - saleor-media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file: common.env
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - STOREFRONT_URL=http://192.168.10.5:3000/
      - DASHBOARD_URL=http://192.168.10.5:9000/
      - ALLOWED_CLIENT_HOSTS="*"
      - ALLOWED_HOSTS="192.168.10.5,*"

  storefront:
    build:
      context: ./saleor-storefront
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./saleor-storefront/:/app:cached
      - /app/node_modules/
    command: npm start -- --host 0.0.0.0
    environment:
      - API_URL=http://192.168.10.5:8000/
      - ALLOWED_CLIENT_HOSTS="*"
      - ALLOWED_HOSTS="192.168.10.5,*"

  dashboard:
    build:
      context: ./saleor-dashboard
      dockerfile: ./Dockerfile.dev
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - ./saleor-dashboard/:/app:cached
      - /app/node_modules/
    command: npm start -- --host 0.0.0.0
    environment:
      - API_URL=http://192.168.10.5:8000/
      - ALLOWED_CLIENT_HOSTS="*"
      - ALLOWED_HOSTS="192.168.10.5,*"

  db:
    image: library/postgres:11.1-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:5.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: common.env
    depends_on:
      - redis
      - mailhog
    volumes:
      - ./saleor/saleor/:/app/saleor:Z,cached
      - ./saleor/templates/:/app/templates:Z,cached
      # shared volume between worker and api for media
      - saleor-media:/app/media
    environment:
      - EMAIL_URL=smtp://mailhog:1025
      - API_URL=http://192.168.10.5:8000/
      - ALLOWED_CLIENT_HOSTS="*"
      - ALLOWED_HOSTS="192.168.10.5,*"

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
```

### Screenshots

![image](https://user-images.githubusercontent.com/715626/101229537-b2437580-366e-11eb-97a7-7bb948c168ee.png)

![image](https://user-images.githubusercontent.com/715626/101229545-bf606480-366e-11eb-86cb-16e0922bc2bb.png)

![image](https://user-images.githubusercontent.com/715626/101229567-d99a4280-366e-11eb-85f3-b78778160124.png)
