### ISSUE TITLE
Pre-commit fails when installing dependencies through Poetry

### ISSUE THREAD

**Issue by onecrayon** [mirumee/saleor#7719]
### What I'm trying to achieve
I am trying to install the pre-commit git hooks without polluting my local system's dependency graph. I am currently using macOS 10.15.7 with Python 3.9 installed via Homebrew.

### Steps to reproduce the problem
With a clean installation of Python 3.9, do the following:

1. Clone the Saleor repo to create a local working copy
2. Install Poetry per https://python-poetry.org/docs/
3. `poetry install`
4. `poetry run pre-commit install`
5. Change a file, and attempt to commit it

### What I expected to happen
Pre-commit hooks should simply work. However, there are multiple failures:

* `mypy` fails because it is being run at the system level, but mypy is installed in the Poetry-managed virtual env. I can work around this by replacing the YAML with:
    ```yaml
      - repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.910
        hooks:
          - id: mypy
            language: system
            entry: poetry run mypy
            exclude: tests/
    ```
* The migrations check fails because it is being run at the system level, and Django is installed in the Poetry-managed virtual env. I can work around this by replacing the YAML with:
    ```yaml
      - repo: local
        hooks:
          - id: migrations-check
            language: system
            name: Check for uncreated migrations.
            entry: poetry run sh -c "./manage.py makemigrations --check --dry-run"
            files: "models\\.py$"
            stages: [commit]
    ```
* The GraphQL schema check is failing because, again, system level. Wrapping the command with `poetry run` **does not work**, however, because it throws the following exception: `ImportError: failed to find libmagic.  Check your installation`.

Has anyone successfully setup pre-commit without polluting their global Python environment?

**System information**

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other
